### ISSUE TITLE
Is there any plan to add promisified versions?

### ISSUE THREAD

**Issue by nolde** [clarkie/dynogels#87] opened 2017-04-19 02:44 UTC
Are there any plans to add promise support in future releases? There are packages that help with that, allowing dual support for node callback pattern and promises.

```
Account.create([item1, item2, item3], function (err, acccounts) {
  console.log('created 3 accounts in DynamoDB', accounts);
});
// or
Account.create([item1, item2, item3]).then(function (acccounts) {
  console.log('created 3 accounts in DynamoDB', accounts);
}).catch(function (err) {
  console.error(err);
});
```
```
BlogPost
  .query('werner@example.com')
  .where('title').beginsWith('Expanding')
  .exec(callback);
// or
BlogPost
  .query('werner@example.com')
  .where('title').beginsWith('Expanding')
  .exec()
  .then(thenCallback, catchCallback);
```

Some of those packages are [hybridify](https://www.npmjs.com/package/hybridify) and [polygoat](https://www.npmjs.com/package/polygoat), and packages like [any-promise](https://github.com/kevinbeaty/any-promise) would allow flexibility of implementation choice.

**Comment by clarkie** [comment] 2017-04-19 08:39
Dupe of #82 

I'd be happy to look at a PR. It may be simpler to pull dynogels-promisified inside here instead for now?

**Closed by clarkie** 2017-04-19 08:39 UTC
